#include <Arduino.h>

#define ALARME_PORTA_SALA 2
#define ALARME_JANELA_SALA 3
#define ALARME_PORTA_COZINHA 4
#define ALARME_JANELA_COZINHA 5

void setup() {
  pinMode(ALARME_JANELA_SALA, INPUT_PULLUP);
  pinMode(ALARME_PORTA_SALA, INPUT_PULLUP);
  pinMode(ALARME_PORTA_COZINHA, INPUT_PULLUP);
  pinMode(ALARME_JANELA_COZINHA, INPUT_PULLUP);
}

void loop() {
}